### ISSUE TITLE
Comment correction

### ISSUE THREAD

**Issue by audeser** [CfKu/tensor-algebra#2]
On SUBROUTINE contract3_t4f_6x6 (res, t4f)
! contracts a 3x3x3x3 tensor: res(6x6) = **t2f**(3x3x3x3) [3rd dimension]
should state ! contracts a 3x3x3x3 tensor: res(6x6) = **t4f**(3x3x3x3) [3rd dimension]

**Comment by CfKu** [comment]
Dear @audeser ,

Thank's again. If you have improvements, feel free to contribute and follow the [GitHub Flow](https://docs.github.com/en/get-started/quickstart/github-flow).
