### ISSUE TITLE
More comments corrections

### ISSUE THREAD

**Issue by audeser** [CfKu/tensor-algebra#3]
I'm not 100% sure, as I'm not english native, but on the extract/contract subroutines, on starting comments, where you use [3rd dimension] I suposse you wanted to say [rank = 3]

**Comment by CfKu** [comment]
Dear @audeser,

Thank's again. If you have any improvements, feel free to contribute and follow the [GitHub Flow](https://docs.github.com/en/get-started/quickstart/github-flow).
